version: "3.7"
services:
  database:
    image: mysql:8.0.28
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: DEALS
  app:
    image: datawarehouse
    links:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database/DEALS
    depends_on:
      - database
    ports:
      - 8081:8081
    build:
      context: .
      dockerfile: Dockerfile